/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package edu.find_my_friends;

public final class Manifest {
    public static final class permission {
        public static final String C2D_MESSAGE="edu.find_my_friends.permission.C2D_MESSAGE";
    }
}
